### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cailloumajor** [cailloumajor/opcua-centrifugo#28]
When stopping the service with OPC-UA disconnected (but having been connected), a SIGSEV is fired:
```
level=info component=proxy listen=:8080
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x67acd6]

goroutine 1 [running]:
github.com/gopcua/opcua/uacp.(*Conn).Close(0xc0001f60e0)
        /go/pkg/mod/github.com/gopcua/opcua@v0.3.2/uacp/conn.go:211 +0x36
github.com/gopcua/opcua.(*Client).CloseWithContext(0xc0001f60e0, {0x86ac28, 0xc000080cc0})
        /go/pkg/mod/github.com/gopcua/opcua@v0.3.2/client.go:588 +0x12a
github.com/cailloumajor/opcua-centrifugo/internal/opcua.(*Client).Close(0xc00029c540, {0x86ac28, 0xc000080cc0})
        /workspaces/opcua-centrifugo/internal/opcua/client.go:146 +0xef
github.com/cailloumajor/opcua-centrifugo/internal/opcua.(*Monitor).Stop(0xc00007fec0, {0x86ac28, 0xc000080cc0})
        /workspaces/opcua-centrifugo/internal/opcua/monitor.go:210 +0x20a
main.main.func8({0x0, 0xc000073440})
        /workspaces/opcua-centrifugo/cmd/opcua-centrifugo/main.go:238 +0x93
github.com/oklog/run.(*Group).Run(0xc0002f9e80)
        /go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:47 +0x12e
main.main()
        /workspaces/opcua-centrifugo/cmd/opcua-centrifugo/main.go:247 +0x1aa7
```

**Comment by cailloumajor** [comment]
This issue can be closed when fixes for issues below are released:
- [ ] https://github.com/gopcua/opcua/issues/567
